### ISSUE TITLE
Sending my private notes in cleartext!

### ISSUE THREAD

**Issue by benwr** [sn-extensions/math-editor#10]
It looks like this editor is based on Upmath, which I can understand as a design decision; you can't build everything from scratch when you're trying to make something like StandardNotes. However, Upmath (and thus this extension) renders LaTeX by sending the math contents _in cleartext_ to a Russian website. For a privacy-centered notes app, this is obviously unacceptable, and there's no warning about it anywhere. This is such an obvious and major mistake that it's putting me off your product entirely.

IMO, this extension should obviously bundle KaTeX or MathJAX instead.

**Comment by benwr** [comment]
It only just occurred to me that I probably should have sent this to security@standardnotes.org instead; I'm sorry that I didn't do that - I'm not at all embedded in the security world, and I didn't think about what procedure to follow. Nonetheless, this is such an obvious issue that I feel confident that any malicious actor will also have thought of it.

**Comment by mobitar** [comment]
We do mention it before you install the editor. We could make it more explicit that your formulas are uploaded to a server though. I’ll look into seeing if this server could be self-hosted by us. ![6A37DCFD-3219-43C8-94F5-846DCAA7745A](https://user-images.githubusercontent.com/3277844/72190786-0a71e900-33c6-11ea-99e6-521b3924a05d.jpeg)

**Comment by benwr** [comment]
StandardNotes hosting it over HTTPS would be an improvement, and I appreciate the fast response time. I still think it would be much better to use bundled KaTeX/MathJAX, if that's a possibility.

Part of the appeal of StandardNotes, at least to me, is the idea that I don't have to trust StandardNotes' (or anyone's) server; I can trust the local frontend software to keep my data safe, and any hosted rendering solution breaks that property for anything rendered.

**Comment by mobitar** [comment]
Yeah, you’re right. We shouldn’t make exceptions for any editor to make external content requests, even for subsets as small as math formulas. This editor is useful beyond just LaTeX rendering however. What I’ve done is removed any math/LaTex related functionality from the editor, which included the image rendering server for equations, and removed any reference of any external non-initial asset urls. What remains is a markdown editor that can convert to HTML, and has a unique take on inline syntax highlighting. It will be a minor inconvenience to anyone who relied on this editor for formulas, but better that they retain access to the overall editing experience they’re familiar with for their associated notes than lose access to the editor completely.

Thanks for surfacing this issue!

**Comment by mobitar** [comment]
Update: local-side rendering has been added via katex thanks to the PR linked above.
